---
# tasks file for maintenance

- name: Install pacman-contrib
  yay: 
    name: pacman-contrib
    state: latest

- name: Copy paccache.timer
  copy:
    src: paccache.timer 
    dest: /etc/systemd/system/paccache.timer

- name: Enable paccache.timer
  systemd:
    name: paccache.timer
    enabled: yes
    state: restarted
