---
- hosts: localhost
  roles:
    - facts
    - base
    - aur_helper
    - env_setup
    - maintenance
    - monitoring
    - python
    - vscodium
    - browsers
    - chats
    - spotify
    - crypto
    - 1password
    - vpn
    - yubikey
    - devices
    - security
...
