---
# tasks file for env-setup

- name: Create group for user
  group:
    name: "{{ target_user }}"
    state: present

- name: Update main group user
  user:
    name: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Update groups of user
  user:
    name: "{{ target_user }}"
    groups: "wheel"
    append: yes

- name: Change home group directory to new group
  file:
    path: "/home/{{ target_user }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Copy scripts 
  template:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.path }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755
  with_community.general.filetree: ../templates/scripts

- name: Install common packages
  yay:
    state: latest
    name: ['curl', 'wget', 'jq', 'dos2unix', 'the_silver_searcher', 'ranger', 'ncdu']

- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true
...
