---
# tasks file for base

- name: "Install base dependencies"
  pacman: 
    name: ["go", "git", "make", "gcc", "patch", "sudo"]
    state: present
  become: true

- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true
